namespace WinModes.Core.Software;

public enum SoftwareAudience
{
    Everyday,
    AiCoding,
}

public enum SoftwareKind { Desktop, Cli, EditorBridge }

/// <summary>Fixed publisher identities and WinGet targets. No user-supplied command is executed.</summary>
public sealed record SoftwareEntry(string Id, string Name, SoftwareAudience Audience, string Category,
    string Description, string Website, string? WingetId = null, string? Note = null, string Source = "winget", SoftwareKind Kind = SoftwareKind.Desktop)
{
    public string? InstallCommand => WingetId is null ? null : $"winget install --id {WingetId} --exact --source {Source} --interactive --no-upgrade --skip-dependencies";
}

public static class SoftwareCatalog
{
    public static IReadOnlyList<SoftwareEntry> Entries { get; } = Array.AsReadOnly<SoftwareEntry>(
    [
        new("firefox", "Firefox", SoftwareAudience.Everyday, "Browsers", "Browse the web with an independent, customizable browser.", "https://www.mozilla.org/firefox/new/", "Mozilla.Firefox"),
        new("brave", "Brave", SoftwareAudience.Everyday, "Browsers", "Browse with built-in tracker and ad blocking.", "https://brave.com/download/", "Brave.Brave"),
        new("obsidian", "Obsidian", SoftwareAudience.Everyday, "Notes & documents", "Connect your notes in a local Markdown vault.", "https://obsidian.md/download", "Obsidian.Obsidian"),
        new("joplin", "Joplin", SoftwareAudience.Everyday, "Notes & documents", "Organize notes and to-do lists with an open-source notebook.", "https://joplinapp.org/help/install/", "Joplin.Joplin"),
        new("libreoffice", "LibreOffice", SoftwareAudience.Everyday, "Notes & documents", "Write documents, work with spreadsheets and create presentations.", "https://www.libreoffice.org/download/", "TheDocumentFoundation.LibreOffice"),
        new("vlc", "VLC", SoftwareAudience.Everyday, "Media & communication", "Play video and audio files with an open-source media player.", "https://www.videolan.org/vlc/", "VideoLAN.VLC"),
        new("spotify", "Spotify", SoftwareAudience.Everyday, "Media & communication", "Listen to music and podcasts on your desktop.", "https://www.spotify.com/download/windows/", "Spotify.Spotify"),
        new("discord", "Discord", SoftwareAudience.Everyday, "Media & communication", "Talk with your communities by text, voice and video.", "https://discord.com/download", "Discord.Discord"),
        new("7zip", "7-Zip", SoftwareAudience.Everyday, "Utilities", "Open and create compressed archives.", "https://www.7-zip.org/", "7zip.7zip"),
        new("powertoys", "PowerToys", SoftwareAudience.Everyday, "Utilities", "Add window layouts, a launcher and other Windows utilities.", "https://learn.microsoft.com/windows/powertoys/install", "Microsoft.PowerToys"),
        new("cursor", "Cursor", SoftwareAudience.AiCoding, "AI editors", "Edit a project with an AI assistant built into the editor.", "https://cursor.com/download", "Anysphere.Cursor", "AI features may require an account or a paid plan."),
        new("t3", "T3 Code", SoftwareAudience.AiCoding, "Desktop coding agents", "Work with coding agents in a desktop workspace.", "https://t3.codes/download", "T3Tools.T3Code", "You may need a separate account for the coding provider you choose."),
        new("opencode", "OpenCode", SoftwareAudience.AiCoding, "Desktop coding agents", "Use a coding agent with a choice of model providers, on the desktop or in a terminal.", "https://opencode.ai/download", "SST.OpenCodeDesktop", "Provider access and billing depend on the model you choose."),
        new("codex", "Codex CLI", SoftwareAudience.AiCoding, "CLI coding agents", "Work on code with OpenAI's coding agent.", "https://github.com/openai/codex", "OpenAI.Codex", "Terminal agent. For the desktop experience with Codex, choose ChatGPT.", Kind: SoftwareKind.Cli),
        new("claude-code", "Claude Code CLI", SoftwareAudience.AiCoding, "CLI coding agents", "Work on a repository with Anthropic's coding agent.", "https://code.claude.com/docs/en/setup", "Anthropic.ClaudeCode", "Follow the official Windows setup guide, including its prerequisites and sign-in.", Kind: SoftwareKind.Cli),
        new("grok-bot", "Grok Bot", SoftwareAudience.AiCoding, "Desktop coding agents", "Give tasks to AI teammates from the Grok Bot desktop app.", "https://x.ai/bot", "xAI.GrokBot", "Check account access and pricing with xAI before installing."),
        new("chatgpt", "ChatGPT", SoftwareAudience.AiCoding, "AI chat apps", "Ask questions, draft text and discuss ideas with ChatGPT.", "https://chatgpt.com/download/", "9PLM9XGG6VKS", "Includes desktop access to Codex. Account features depend on your plan.", "msstore"),
        new("claude", "Claude Desktop", SoftwareAudience.AiCoding, "AI chat apps", "Chat with Claude from the desktop app.", "https://claude.com/download", "Anthropic.Claude", "This is the desktop app; Claude Code has a separate setup guide."),
        new("vscode", "Visual Studio Code", SoftwareAudience.AiCoding, "Code editors", "Use a general-purpose code editor with extensions.", "https://code.visualstudio.com/download", "Microsoft.VisualStudioCode"),
        new("git", "Git", SoftwareAudience.AiCoding, "Developer essentials", "Track changes and work with Git repositories.", "https://git-scm.com/downloads/win", "Git.Git", Kind: SoftwareKind.Cli),
        new("node", "Node.js LTS", SoftwareAudience.AiCoding, "Developer essentials", "Run JavaScript tools and npm packages with the LTS runtime.", "https://nodejs.org/en/download", "OpenJS.NodeJS.LTS", Kind: SoftwareKind.Cli),
        new("docker", "Docker Desktop", SoftwareAudience.AiCoding, "Developer essentials", "Build and run local containers.", "https://www.docker.com/products/docker-desktop/", "Docker.DockerDesktop", "Review Docker's license and Windows requirements. Setup may require a restart."),
        new("chrome", "Google Chrome", SoftwareAudience.Everyday, "Browsers", "Browse with Google's browser.", "https://www.google.com/chrome/", "Google.Chrome"),
        new("vivaldi", "Vivaldi", SoftwareAudience.Everyday, "Browsers", "Customize tabs, workspaces and your browsing layout.", "https://vivaldi.com/", "Vivaldi.Vivaldi"),
        new("thunderbird", "Thunderbird", SoftwareAudience.Everyday, "Media & communication", "Manage email accounts and calendars in one app.", "https://www.thunderbird.net/", "Mozilla.Thunderbird"),
        new("signal", "Signal", SoftwareAudience.Everyday, "Media & communication", "Use private messaging linked to your phone.", "https://signal.org/", "OpenWhisperSystems.Signal"),
        new("telegram", "Telegram", SoftwareAudience.Everyday, "Media & communication", "Chat and share files with Telegram Desktop.", "https://desktop.telegram.org/", "Telegram.TelegramDesktop"),
        new("sumatra", "SumatraPDF", SoftwareAudience.Everyday, "Notes & documents", "Read PDFs and ebooks with a lightweight viewer.", "https://www.sumatrapdfreader.org/", "SumatraPDF.SumatraPDF"),
        new("notepadplusplus", "Notepad++", SoftwareAudience.Everyday, "Notes & documents", "Edit text files and code with a compact editor.", "https://notepad-plus-plus.org/", "Notepad++.Notepad++"),
        new("bitwarden", "Bitwarden", SoftwareAudience.Everyday, "Passwords", "Manage passwords in an encrypted vault.", "https://bitwarden.com/", "Bitwarden.Bitwarden"),
        new("keepassxc", "KeePassXC", SoftwareAudience.Everyday, "Passwords", "Keep passwords in a local encrypted database.", "https://keepassxc.org/", "KeePassXCTeam.KeePassXC"),
        new("peazip", "PeaZip", SoftwareAudience.Everyday, "Utilities", "Manage compressed archives with a graphical file manager.", "https://peazip.github.io/", "Giorgiotani.Peazip"),
        new("everything", "Everything", SoftwareAudience.Everyday, "Utilities", "Find files quickly by name.", "https://www.voidtools.com/", "voidtools.Everything"),
        new("sharex", "ShareX", SoftwareAudience.Everyday, "Utilities", "Capture screenshots and record your screen.", "https://getsharex.com/", "ShareX.ShareX", "Review upload settings before sharing a capture."),
        new("rufus", "Rufus", SoftwareAudience.Everyday, "Utilities", "Create bootable USB drives when you need them.", "https://rufus.ie/", "Rufus.Rufus", "Creating a USB drive erases its contents. Installation alone does not format a drive."),
        new("obs", "OBS Studio", SoftwareAudience.Everyday, "Creative tools", "Record video and stream with customizable scenes.", "https://obsproject.com/", "OBSProject.OBSStudio"),
        new("audacity", "Audacity", SoftwareAudience.Everyday, "Creative tools", "Record and edit audio tracks.", "https://www.audacityteam.org/", "Audacity.Audacity"),
        new("gimp", "GIMP", SoftwareAudience.Everyday, "Creative tools", "Edit images with an open-source image editor.", "https://www.gimp.org/", "GIMP.GIMP.3"),
        new("paintnet", "Paint.NET", SoftwareAudience.Everyday, "Creative tools", "Edit photos and images with layers and effects.", "https://www.getpaint.net/", "dotPDN.PaintDotNet"),
        new("inkscape", "Inkscape", SoftwareAudience.Everyday, "Creative tools", "Draw vector illustrations and edit SVG files.", "https://inkscape.org/", "Inkscape.Inkscape"),
        new("handbrake", "HandBrake", SoftwareAudience.Everyday, "Creative tools", "Convert video files between formats.", "https://handbrake.fr/", "HandBrake.HandBrake"),
        new("steam", "Steam", SoftwareAudience.Everyday, "Gaming", "Install and manage games in your Steam library.", "https://store.steampowered.com/", "Valve.Steam"),
        new("epic", "Epic Games Launcher", SoftwareAudience.Everyday, "Gaming", "Install and manage your Epic Games library.", "https://store.epicgames.com/", "EpicGames.EpicGamesLauncher"),
        new("qbittorrent", "qBittorrent", SoftwareAudience.Everyday, "Utilities", "Manage BitTorrent downloads with an open-source client.", "https://www.qbittorrent.org/", "qBittorrent.qBittorrent"),
        new("rustdesk", "RustDesk", SoftwareAudience.Everyday, "Utilities", "Connect to another computer for remote support.", "https://rustdesk.com/", Note: "Not currently available in the verified WinGet source. Remote access requires care."),
        new("python", "Python", SoftwareAudience.AiCoding, "Developer essentials", "Run Python scripts and development tools.", "https://www.python.org/", "Python.Python.3.14", Kind: SoftwareKind.Cli),
        new("powershell", "PowerShell", SoftwareAudience.AiCoding, "Developer essentials", "Use the modern PowerShell terminal and scripting runtime.", "https://github.com/PowerShell/PowerShell", "Microsoft.PowerShell", Kind: SoftwareKind.Cli),
        new("opencode-cli", "OpenCode CLI", SoftwareAudience.AiCoding, "CLI coding agents", "Run OpenCode directly in your terminal.", "https://opencode.ai/docs/", "SST.opencode", "Provider access and billing depend on the model you choose.", Kind: SoftwareKind.Cli),
        new("blender", "Blender", SoftwareAudience.Everyday, "Creative tools", "Create 3D models, animations and renders.", "https://www.blender.org/", "BlenderFoundation.Blender"),
        new("calibre", "Calibre", SoftwareAudience.Everyday, "Notes & documents", "Organize your ebook library and convert ebook formats.", "https://calibre-ebook.com/", "calibre.calibre"),
        new("zotero", "Zotero", SoftwareAudience.Everyday, "Notes & documents", "Collect research sources and manage citations.", "https://www.zotero.org/", "DigitalScholar.Zotero"),
        new("localsend", "LocalSend", SoftwareAudience.Everyday, "File sharing & network", "Send files between devices on your local network.", "https://localsend.org/", "LocalSend.LocalSend"),
        new("syncthing", "Syncthing", SoftwareAudience.Everyday, "File sharing & network", "Synchronize chosen folders between your devices.", "https://syncthing.net/", "Syncthing.Syncthing", "Choose shared folders carefully. Changes and deletions can synchronize to other devices."),
        new("winscp", "WinSCP", SoftwareAudience.Everyday, "File sharing & network", "Transfer files securely using SFTP and SCP.", "https://winscp.net/", "WinSCP.WinSCP"),
        new("tailscale", "Tailscale", SoftwareAudience.Everyday, "File sharing & network", "Connect your devices through a private network.", "https://tailscale.com/", "Tailscale.Tailscale", "Requires an account. Review network access before connecting devices."),
        new("playnite", "Playnite", SoftwareAudience.Everyday, "Gaming", "Bring game libraries together in one launcher.", "https://playnite.link/", "Playnite.Playnite"),
        new("gog", "GOG Galaxy", SoftwareAudience.Everyday, "Gaming", "Install and manage games from your GOG library.", "https://www.gog.com/galaxy", "GOG.Galaxy"),
        new("wiztree", "WizTree", SoftwareAudience.Everyday, "Diagnostics", "See which files and folders use your disk space.", "https://wiztreefree.com/", "AntibodySoftware.WizTree"),
        new("hwinfo", "HWiNFO", SoftwareAudience.Everyday, "Diagnostics", "Inspect hardware specifications and sensor readings.", "https://www.hwinfo.com/", "REALiX.HWiNFO"),
        new("crystaldiskinfo", "CrystalDiskInfo", SoftwareAudience.Everyday, "Diagnostics", "Read disk health and temperature information.", "https://crystalmark.info/en/software/crystaldiskinfo/", "CrystalDewWorld.CrystalDiskInfo"),
        new("cpuz", "CPU-Z", SoftwareAudience.Everyday, "Diagnostics", "Inspect your processor, motherboard and memory.", "https://www.cpuid.com/softwares/cpu-z.html", "CPUID.CPU-Z"),
        new("gpuz", "GPU-Z", SoftwareAudience.Everyday, "Diagnostics", "Inspect your graphics card and its sensors.", "https://www.techpowerup.com/gpuz/", "TechPowerUp.GPU-Z"),
        new("1password", "1Password", SoftwareAudience.Everyday, "Passwords", "Store passwords and share vaults with your family or team.", "https://1password.com/", "AgileBits.1Password", "Requires an account and a subscription after the trial."),
        new("foobar", "foobar2000", SoftwareAudience.Everyday, "Media & communication", "Play and organize music with a customizable audio player.", "https://www.foobar2000.org/", "PeterPawlowski.foobar2000"),
        new("aimp", "AIMP", SoftwareAudience.Everyday, "Media & communication", "Listen to music and manage playlists with an audio player.", "https://www.aimp.ru/", "AIMP.AIMP"),
        new("zoom", "Zoom", SoftwareAudience.Everyday, "Media & communication", "Join video meetings and share your screen.", "https://zoom.us/", "Zoom.Zoom"),

        new("edge", "Microsoft Edge", SoftwareAudience.Everyday, "Browsers", "Browse with Microsoft's browser and integrated Windows features.", "https://www.microsoft.com/edge", "Microsoft.Edge"),
        new("firefox-esr", "Firefox ESR", SoftwareAudience.Everyday, "Browsers", "Use Firefox's extended-support release for a steadier update schedule.", "https://www.mozilla.org/firefox/enterprise/", "Mozilla.Firefox.ESR"),
        new("floorp", "Floorp", SoftwareAudience.Everyday, "Browsers", "Customize a Firefox-based browser with flexible workspaces.", "https://floorp.app/", "Ablaze.Floorp"),
        new("helium", "Helium", SoftwareAudience.Everyday, "Browsers", "Browse with an open-source Chromium-based browser.", "https://helium.computer/", "ImputNet.Helium"),
        new("librewolf", "LibreWolf", SoftwareAudience.Everyday, "Browsers", "Use a Firefox-based browser focused on privacy.", "https://librewolf.net/", "LibreWolf.LibreWolf"),
        new("mullvad-browser", "Mullvad Browser", SoftwareAudience.Everyday, "Browsers", "Browse with protections designed to reduce fingerprinting.", "https://mullvad.net/browser", "MullvadVPN.MullvadBrowser", "This browser does not install or include a VPN subscription."),
        new("tor", "Tor Browser", SoftwareAudience.Everyday, "Browsers", "Browse through the Tor network with a dedicated browser.", "https://www.torproject.org/", "TorProject.TorBrowser"),
        new("waterfox", "Waterfox", SoftwareAudience.Everyday, "Browsers", "Browse with an independent Firefox-based browser.", "https://www.waterfox.net/", "Waterfox.Waterfox"),
        new("zen", "Zen Browser", SoftwareAudience.Everyday, "Browsers", "Organize browsing with vertical tabs and workspaces.", "https://zen-browser.app/", "Zen-Team.Zen-Browser"),
        new("ungoogled", "Ungoogled Chromium", SoftwareAudience.Everyday, "Browsers", "Use Chromium with Google-specific integrations removed.", "https://github.com/Eloston/ungoogled-chromium", "eloston.ungoogled-chromium", "Windows binaries are community builds. Review extension and update support."),
        new("opera", "Opera", SoftwareAudience.Everyday, "Browsers", "Browse with Opera's sidebar and workspace features.", "https://www.opera.com/", "Opera.Opera"),
        new("opera-gx", "Opera GX", SoftwareAudience.Everyday, "Browsers", "Use Opera's browser with gaming-oriented customization.", "https://www.opera.com/gx", "Opera.OperaGX"),
        new("onlyoffice", "ONLYOFFICE Desktop Editors", SoftwareAudience.Everyday, "Notes & documents", "Edit documents, spreadsheets and presentations on your desktop.", "https://www.onlyoffice.com/desktop.aspx", "ONLYOFFICE.DesktopEditors"),
        new("pdfgear", "PDFgear", SoftwareAudience.Everyday, "Notes & documents", "Read, annotate and edit PDF documents.", "https://www.pdfgear.com/", "PDFgear.PDFgear"),
        new("logseq", "Logseq", SoftwareAudience.Everyday, "Notes & documents", "Organize linked notes and outlines in a knowledge base.", "https://logseq.com/", "Logseq.Logseq"),
        new("proton-pass", "Proton Pass", SoftwareAudience.Everyday, "Passwords", "Manage passwords and aliases with Proton's password manager.", "https://proton.me/pass", "Proton.ProtonPass"),
        new("keepass", "KeePass", SoftwareAudience.Everyday, "Passwords", "Store passwords in a local encrypted database with plugins.", "https://keepass.info/", "DominikReichl.KeePass"),
        new("proton-authenticator", "Proton Authenticator", SoftwareAudience.Everyday, "Passwords", "Generate two-factor authentication codes on your desktop.", "https://proton.me/authenticator", "Proton.ProtonAuthenticator"),
        new("element", "Element", SoftwareAudience.Everyday, "Media & communication", "Chat and call through the Matrix messaging network.", "https://element.io/", "Element.Element"),
        new("mumble", "Mumble", SoftwareAudience.Everyday, "Media & communication", "Use open-source voice chat for groups and communities.", "https://www.mumble.info/", "Mumble.Mumble.Client"),
        new("proton-mail", "Proton Mail", SoftwareAudience.Everyday, "Media & communication", "Use Proton Mail and Calendar from your desktop.", "https://proton.me/mail", "Proton.ProtonMail", "Desktop access depends on your Proton plan."),
        new("potplayer", "PotPlayer", SoftwareAudience.Everyday, "Media & communication", "Play videos with a configurable Windows media player.", "https://potplayer.tv/", "Daum.PotPlayer"),
        new("nanazip", "NanaZip", SoftwareAudience.Everyday, "Utilities", "Manage archives with integration into Windows 11 menus.", "https://nanazip.org/", "M2Team.NanaZip"),
        new("unigetui", "UniGetUI", SoftwareAudience.Everyday, "Utilities", "Browse package managers through a graphical interface.", "https://devolutions.net/unigetui/", "Devolutions.UniGetUI", "WinModes installs this app through WinGet only. UniGetUI manages its own settings and actions."),
        new("advanced-renamer", "Advanced Renamer", SoftwareAudience.Everyday, "Utilities", "Preview and rename groups of files using reusable rules.", "https://www.advancedrenamer.com/", "HulubuluSoftware.AdvancedRenamer"),
        new("krita", "Krita", SoftwareAudience.Everyday, "Creative tools", "Paint and illustrate with an open-source digital art studio.", "https://krita.org/", "KDE.Krita"),
        new("kdenlive", "Kdenlive", SoftwareAudience.Everyday, "Creative tools", "Edit videos with an open-source timeline editor.", "https://kdenlive.org/", "KDE.Kdenlive"),
        new("darktable", "darktable", SoftwareAudience.Everyday, "Creative tools", "Develop RAW photos and organize your photography workflow.", "https://www.darktable.org/", "darktable.darktable"),
        new("freecad", "FreeCAD", SoftwareAudience.Everyday, "Creative tools", "Design parametric 3D models and mechanical parts.", "https://www.freecad.org/", "FreeCAD.FreeCAD"),
        new("ea", "EA app", SoftwareAudience.Everyday, "Gaming", "Install and manage games from your EA library.", "https://www.ea.com/ea-app", "ElectronicArts.EADesktop"),
        new("ubisoft", "Ubisoft Connect", SoftwareAudience.Everyday, "Gaming", "Install and manage games from your Ubisoft library.", "https://ubisoftconnect.com/", "Ubisoft.Connect"),
        new("nextcloud", "Nextcloud Desktop", SoftwareAudience.Everyday, "File sharing & network", "Synchronize files with your Nextcloud account or server.", "https://nextcloud.com/install/", "Nextcloud.NextcloudDesktop"),
        new("proton-drive", "Proton Drive", SoftwareAudience.Everyday, "File sharing & network", "Synchronize chosen files with encrypted cloud storage.", "https://proton.me/drive", "Proton.ProtonDrive"),
        new("filezilla", "FileZilla", SoftwareAudience.Everyday, "File sharing & network", "Transfer files using FTP, FTPS and SFTP.", "https://filezilla-project.org/", Note: "No package is currently available in the verified WinGet source. See the official guide."),
        new("process-explorer", "Process Explorer", SoftwareAudience.Everyday, "Diagnostics", "Inspect running processes, handles and loaded libraries.", "https://learn.microsoft.com/sysinternals/downloads/process-explorer", "Microsoft.Sysinternals.ProcessExplorer"),
        new("process-monitor", "Process Monitor", SoftwareAudience.Everyday, "Diagnostics", "Inspect file, registry and process activity for troubleshooting.", "https://learn.microsoft.com/sysinternals/downloads/procmon", "Microsoft.Sysinternals.ProcessMonitor"),
        new("crystaldiskmark", "CrystalDiskMark", SoftwareAudience.Everyday, "Diagnostics", "Measure disk read and write performance.", "https://crystalmark.info/en/software/crystaldiskmark/", "CrystalDewWorld.CrystalDiskMark", "Benchmarks write test data. Installation does not start a benchmark."),
        new("vscodium", "VSCodium", SoftwareAudience.AiCoding, "Code editors", "Use an open-source distribution of VS Code without Microsoft's product customizations.", "https://vscodium.com/", "VSCodium.VSCodium", "Uses Open VSX. Some Microsoft extensions and services may not be available."),
        new("zed", "Zed", SoftwareAudience.AiCoding, "Code editors", "Edit code with an open-source editor and integrated coding agents.", "https://zed.dev/", "ZedIndustries.Zed"),
        new("windsurf", "Windsurf", SoftwareAudience.AiCoding, "AI editors", "Work with an AI coding editor and its project assistant.", "https://windsurf.com/", "Codeium.Windsurf", "AI features may require an account or a paid plan."),
        new("void", "Void", SoftwareAudience.AiCoding, "AI editors", "Use an open-source AI editor based on VS Code with a choice of model providers.", "https://voideditor.com/", "GlassDevtools.Void", "Beta software. Model access and billing depend on your provider."),
        new("ollama", "Ollama", SoftwareAudience.AiCoding, "Local AI", "Run supported Mistral, DeepSeek and other models locally on Windows.", "https://ollama.com/", "Ollama.Ollama", "Models are downloaded separately and need disk space and suitable RAM or GPU memory."),
        new("lmstudio", "LM Studio", SoftwareAudience.AiCoding, "Local AI", "Explore local models and run them through a desktop interface.", "https://lmstudio.ai/", "ElementLabs.LMStudio", "Models are downloaded separately and need disk space and suitable RAM or GPU memory."),
        new("jan", "Jan", SoftwareAudience.AiCoding, "Local AI", "Use an open-source desktop app for local models and compatible AI providers.", "https://jan.ai/", "Jan.Jan", "Models are downloaded separately and need disk space and suitable RAM or GPU memory."),
        new("gemini", "Gemini Desktop", SoftwareAudience.AiCoding, "AI chat apps", "Use Google's official Gemini desktop app.", "https://gemini.google/desktop/", "Google.GeminiDesktop", "Account features depend on your Google plan."),
        new("copilot-cli", "GitHub Copilot CLI", SoftwareAudience.AiCoding, "CLI coding agents", "Work with GitHub's coding agent from your terminal.", "https://github.com/github/copilot-cli", "GitHub.Copilot", "Requires access to GitHub Copilot.", Kind: SoftwareKind.Cli),
        new("mistral-vibe", "Mistral Vibe CLI", SoftwareAudience.AiCoding, "CLI coding agents", "Use Mistral's official coding assistant from your terminal.", "https://docs.mistral.ai/vibe/code/cli/install-setup", Note: "No verified standalone CLI package in WinGet. The official Windows setup uses uv; the ACP package is a different integration.", Kind: SoftwareKind.Cli),
        new("mistral-acp", "Mistral Vibe ACP", SoftwareAudience.AiCoding, "Editor integrations", "Connect an ACP-compatible editor to Mistral Vibe.", "https://github.com/mistralai/mistral-vibe", "MistralAI.MistralVibe.ACP", "Editor bridge using vibe-acp. This is not the standalone interactive Vibe CLI.", Kind: SoftwareKind.EditorBridge),
        new("deepseek-harness", "DeepSeek Harness Desktop", SoftwareAudience.AiCoding, "Desktop coding agents", "Use DeepSeek's official desktop agent for work with local files and projects.", "https://www.deepseek.com/en/download/", Note: "Official Windows app available from DeepSeek. No verified official WinGet package; similarly named community clients are different products."),
        new("github-cli", "GitHub CLI", SoftwareAudience.AiCoding, "Developer essentials", "Manage GitHub repositories, issues and pull requests from your terminal.", "https://cli.github.com/", "GitHub.cli", Kind: SoftwareKind.Cli),
        new("github-desktop", "GitHub Desktop", SoftwareAudience.AiCoding, "Developer essentials", "Review changes and work with Git repositories through a desktop app.", "https://desktop.github.com/", "GitHub.GitHubDesktop"),
        new("uv", "uv", SoftwareAudience.AiCoding, "Developer essentials", "Manage Python tools, environments and dependencies.", "https://docs.astral.sh/uv/", "astral-sh.uv", Kind: SoftwareKind.Cli),
        new("bruno", "Bruno", SoftwareAudience.AiCoding, "Developer essentials", "Test APIs with collections stored in your project files.", "https://www.usebruno.com/", "Bruno.Bruno"),
        new("neovim", "Neovim", SoftwareAudience.AiCoding, "Code editors", "Edit code in your terminal with an extensible open-source editor.", "https://neovim.io/", "Neovim.Neovim", Kind: SoftwareKind.Cli),
        new("jetbrains", "JetBrains Toolbox", SoftwareAudience.AiCoding, "Developer essentials", "Manage JetBrains development tools and their updates.", "https://www.jetbrains.com/toolbox-app/", "JetBrains.Toolbox", "Individual IDE licenses and AI features have their own terms."),
        new("duckduckgo", "DuckDuckGo", SoftwareAudience.Everyday, "Browsers", "Browse with DuckDuckGo's privacy-focused Windows browser.", "https://duckduckgo.com/app", "DuckDuckGo.DesktopBrowser"),
        new("thorium", "Thorium", SoftwareAudience.Everyday, "Browsers", "Use a Chromium-based browser with performance-oriented builds.", "https://thorium.rocks/", "Alex313031.Thorium"),
        new("mercury", "Mercury", SoftwareAudience.Everyday, "Browsers", "Use a Firefox-based browser with performance-oriented builds.", "https://thorium.rocks/mercury", "Alex313031.Mercury"),
        new("palemoon", "Pale Moon", SoftwareAudience.Everyday, "Browsers", "Browse with an independent open-source browser and its own extension ecosystem.", "https://www.palemoon.org/", "MoonchildProductions.PaleMoon"),
        new("maxthon", "Maxthon", SoftwareAudience.Everyday, "Browsers", "Browse with Maxthon's tabs, account and workspace features.", "https://www.maxthon.com/", "Maxthon.Maxthon"),
    ]);
}
